version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: KAMAL
      DB_USER: root
      DB_PASSWORD: locuz@123
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: KAMAL
      MYSQL_USER: root
      MYSQL_PASSWORD: locuz@123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
