version: '3.10'

services:
  web:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile  # Path to Dockerfile
    command: ./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    ports:
      - "8000:8000"  # Map port 8000 from container to host
    environment:
      DB_NAME: KAMAL
      DB_USER: root
      DB_PASSWORD: locuz@123
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db  # Ensures that db is started before the web service

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: KAMAL
      MYSQL_USER: root
      MYSQL_PASSWORD: locuz@123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

volumes:
  mysql_data:  # Define a volume for MySQL data persistence
