version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: locuz@123
      MYSQL_DATABASE: KAMAL
      MYSQL_USER: root
      MYSQL_PASSWORD: locuz@123
    networks:
      - app_network

  docapp-container:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DB_NAME: KAMAL
      DB_USER: root
      DB_PASSWORD: locuz@123
      DB_HOST: localhost  # Set to localhost for local development
      DB_PORT: 3306
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
